name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: tj-actions/branch-names@v6
        id: branch-name

      - uses: actions/checkout@v3
      
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: cuotos
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: release
        if: steps.branch-name.outputs.is_default == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: cuotos/webtester:latest,cuotos/webtester:blue,cuotos/webtester:green

      - name: release test
        if: steps.branch-name.outputs.is_default == 'false'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: cuotos/webtester:test,cuotos/webtester:${{ steps.branch-name.outputs.current_branch }}